name: Build and Deploy
on:
  push:
    branches:
      - src
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: npm install, build and deploy
          run: |
            npm install
            npm run build
            npm run deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
